Notifiec
ius-csg/csgAutomations pull request #1
Opened 2020-12-31 06:56 UTC by Cliftonz

added discord notfication script

2020-12-31 18:53 UTC, Cliftonz commented
Changes and updates are prepped and ready on Rundeck.

2021-01-02 03:01 UTC, TheOtherUnknown commented
I'll poke though this on Rundeck sometime this weekend. Looks pretty good though

2021-01-02 04:12 UTC, Cliftonz commented
@TheOtherUnknown thid is not put out on rundeck yet till it gets approved and merged to master, but the job is set up and ready to go. I would look at the phrasing or the notifications to make sure they sounds correct.

2021-01-03 02:50 UTC, TheOtherUnknown requested changes
Few typos, but looks okay. I'll be interested to see this working.

2021-01-03 02:50 UTC, TheOtherUnknown commented on EventNotifier.py
> +                                                      f"We hope to see everyone their!\n"
`
```suggestion
                                                      f"We hope to see everyone there!\n"
```

2021-01-03 02:50 UTC, TheOtherUnknown commented on EventNotifier.py
> +                                             f"Please do not forget to sign up if your interested. \n"
```suggestion
                                             f"Please do not forget to sign up if you are interested. \n"
```

2021-01-03 02:50 UTC, TheOtherUnknown commented on EventNotifier.py
> +                                             f" Please do not forget to sign up if your interested. \n"
```suggestion
                                             f" Please do not forget to sign up if you are interested. \n"
```

2021-01-03 02:50 UTC, TheOtherUnknown commented on EventNotifier.py
> +                                             f"We hope to see everyone their!\n"
```suggestion
                                             f"We hope to see everyone there!\n"
```

2021-01-03 04:24 UTC, AStiner reviewed
I agree with Adam's changes.

2021-01-04 04:10 UTC, AStiner approved these changes
Approve changes

2021-01-04 04:11 UTC, merged